import type { CommandExecutor } from "./types";

const CATALOG_URL =
  "https://www.twilio.com/docs/segment/connections/destinations/catalog/index-all";

const extractDestinationNames = (html: string): ReadonlyArray<string> => {
  const names: string[] = [];
  const linkPattern = /<a[^>]*class="[^"]*destination[^"]*"[^>]*>([^<]+)<\/a>/gi;
  let match: RegExpExecArray | null;

  while ((match = linkPattern.exec(html)) !== null) {
    const name = match[1].trim();
    if (name) names.push(name);
  }

  if (names.length > 0) return names;

  const listItemPattern = /<li[^>]*>\s*<a[^>]*>([^<]+)<\/a>/gi;
  while ((match = listItemPattern.exec(html)) !== null) {
    const name = match[1].trim();
    if (name) names.push(name);
  }

  return names;
};

export const fetchCatalogDestinations = async (
  execute: CommandExecutor
): Promise<ReadonlyArray<string>> => {
  const html = execute(
    `api --method GET -H "Accept: text/html" "${CATALOG_URL}" 2>/dev/null || echo ""`
  );

  if (html && html.includes("destination")) {
    return extractDestinationNames(html);
  }

  return FALLBACK_CATALOG;
};

export const FALLBACK_CATALOG: ReadonlyArray<string> = [
  "1Flow",
  "1Flow Mobile Plugin",
  "1Flow Web (Actions)",
  "2mee",
  "Aampe",
  "Aampe (Actions)",
  "AB Smartly",
  "AB Tasty client side",
  "ABsmartly (Actions)",
  "Accoil Analytics",
  "Acoustic (Actions)",
  "Actable Predictive",
  "Actions Pipedrive",
  "ActiveCampaign",
  "Adikteev",
  "Adjust",
  "Adobe Analytics",
  "Adobe Target Cloud Mode",
  "Adobe Target Web",
  "AdQuick",
  "AdRoll",
  "Adtriba",
  "Aggregations.io (Actions)",
  "Airship",
  "Airship (Actions)",
  "Akita Customer Success",
  "Alexa",
  "Algolia Insights (Actions)",
  "Amazon Ads DSP and AMC",
  "Amazon Conversions Api",
  "Amazon EventBridge",
  "Amazon EventBridge (Actions)",
  "Amazon Kinesis",
  "Amazon Kinesis Firehose",
  "Amazon Lambda",
  "Amazon Personalize",
  "Ambassador",
  "Amberflo",
  "Amplitude",
  "Amplitude (Actions)",
  "Angler AI",
  "Anodot",
  "Appcues",
  "AppFit",
  "AppsFlyer",
  "Apptimize",
  "Asayer",
  "Astrolabe",
  "Atatus",
  "Attentive Mobile",
  "Attio (Actions)",
  "Attribution",
  "Auryc",
  "AutopilotHQ",
  "AWS S3",
  "Azure Function",
  "Batch (Actions)",
  "Beamer",
  "Bing Ads",
  "Blackbaud Raiser's Edge NXT",
  "Blend Ai",
  "Blendo",
  "Blitzllama",
  "Bloomreach Engagement",
  "Branch Metrics",
  "Braze",
  "Braze Cloud Mode (Actions)",
  "Braze Cohorts",
  "Braze Web Device Mode (Actions)",
  "Breyta CRM",
  "Bronto",
  "BugHerd",
  "Bugsnag",
  "Button",
  "BuzzBoard",
  "ByteGain",
  "BytePlus",
  "Calixa",
  "Callingly",
  "Candu",
  "Canny (Actions)",
  "Castle",
  "Chameleon",
  "Chartbeat",
  "ChartMogul",
  "Churned",
  "ChurnZero",
  "Clearbit Enrichment",
  "Clearbit Reveal",
  "ClearBrain",
  "CleverTap",
  "CleverTap (Actions)",
  "Clicky",
  "ClientSuccess",
  "Cliff",
  "Close",
  "Collab Travel CRM",
  "CommandBar",
  "comScore",
  "Contentstack Cloud",
  "Contentstack Web",
  "ConvertFlow",
  "Convertly",
  "Convertro",
  "Cordial (Actions)",
  "Correlated",
  "Countly",
  "Courier",
  "Crazy Egg",
  "Crisp",
  "Criteo App & Web Events",
  "Criteo Audiences",
  "Crittercism",
  "Crossing Minds",
  "CrowdPower",
  "Cruncher",
  "Custify",
  "Customer.io",
  "Customer.io (Actions)",
  "Data Lakes",
  "Delighted",
  "Delivr.ai Resolve",
  "Display and Video 360 (Actions)",
  "Dotdigital",
  "DoubleClick Floodlight",
  "Dreamdata",
  "Drip",
  "Drip (Actions)",
  "Dub (Actions)",
  "Dynamic Yield by Mastercard Audiences",
  "Eagle Eye",
  "Elevio",
  "Eloqua",
  "Emarsys",
  "Emarsys (Actions)",
  "EMMA",
  "Encharge (Actions)",
  "Engage Messaging",
  "EnjoyHQ",
  "EPICA",
  "Equals",
  "Errorception",
  "events.win",
  "Everflow",
  "Experiments by GrowthHackers",
  "Extensible Webhook",
  "Extole Platform",
  "Facebook App Events",
  "Facebook Conversions API (Actions)",
  "Facebook Custom Audiences (Actions)",
  "Facebook Pixel",
  "FactorsAI",
  "Firebase",
  "First Party Dv360",
  "FL0",
  "Flagship.io",
  "Flurry",
  "FoxMetrics",
  "Freshmarketer",
  "Freshsales",
  "Freshsales Suite - CRM",
  "Friendbuy (Cloud Destination)",
  "Friendbuy (Legacy)",
  "Friendbuy (Web Destination)",
  "FullStory",
  "Fullstory (Actions)",
  "Fullstory Cloud Mode (Actions)",
  "FunnelEnvy",
  "FunnelFox",
  "Gainsight",
  "Gainsight PX",
  "Gainsight Px Cloud (Actions)",
  "Gameball (Actions)",
  "Gauges",
  "Gist",
  "Gleap (Action)",
  "Google Ads (Classic)",
  "Google Ads (Gtag)",
  "Google Ads Conversions",
  "Google Ads Remarketing Lists",
  "Google Analytics 4 Cloud",
  "Google Analytics 4 Web",
  "Google Cloud Function",
  "Google Cloud PubSub",
  "Google Cloud Storage",
  "Google Sheets",
  "Google Tag Manager",
  "GoSquared",
  "GraphJSON",
  "Groundswell",
  "GWEN (Actions)",
  "Hawkei",
  "Heap",
  "Help Scout",
  "HitTail",
  "Hotjar",
  "Houseware",
  "Hubble (Actions)",
  "HubSpot",
  "HubSpot Cloud Mode (Actions)",
  "HubSpot Web (Actions)",
  "Humanic AI",
  "hydra",
  "Impact Partnership Cloud",
  "Indicative",
  "Inflection",
  "Inleads AI",
  "InMoment (formerly Wootric)",
  "Innovid",
  "Insider Audiences",
  "Insider Cloud Mode (Actions)",
  "Inspectlet",
  "Intercom",
  "Intercom Cloud Mode (Actions)",
  "Intercom Web (Actions)",
  "Iron.io",
  "Iterable",
  "Iterable (Actions)",
  "Iterate Web (Actions)",
  "Jimo",
  "Jimo (Actions)",
  "Jivox",
  "journy io",
  "June",
  "June (Actions)",
  "Kable",
  "Kafka",
  "Kahuna",
  "Kameleoon (Actions)",
  "Kana",
  "Keen",
  "Kevel",
  "Kissmetrics",
  "Kitemetrics",
  "Klaviyo",
  "Klaviyo (Actions)",
  "Koala",
  "Koala (Cloud)",
  "Kochava",
  "Kubit",
  "Kustomer",
  "LaunchDarkly (Actions)",
  "LaunchDarkly Audiences",
  "Leanplum",
  "Learndot",
  "Librato",
  "LinkedIn Audiences",
  "LinkedIn Conversions API",
  "LinkedIn Insight Tag",
  "Listrak (Actions)",
  "LiveChat",
  "LiveIntent Audiences",
  "LiveLike",
  "LiveRamp Audiences",
  "Localytics",
  "LogRocket",
  "Loops (Actions)",
  "Lou",
  "Lumen",
  "Lucky Orange",
  "Lytics",
  "mabl",
  "Madkudu",
  "Mailchimp",
  "Mailjet",
  "Mailmodo",
  "Mammoth",
  "Marketo Static Lists (Actions)",
  "Marketo V2",
  "Markettailor",
  "Matcha",
  "Matilda",
  "Matomo",
  "Metronome (Actions)",
  "Millennial Media",
  "Mixpanel (Actions)",
  "Mixpanel (Legacy)",
  "Mixpanel Web (actions)",
  "MoEngage",
  "Moengage (Actions)",
  "Moesif API Analytics",
  "Moloco MCM",
  "Monetate",
  "Moosend",
  "Mouseflow",
  "Movable Ink (Actions)",
  "Mutiny",
  "Nanigans",
  "Nat",
  "Natero",
  "New Relic",
  "Nielsen DCR",
  "Ninetailed by Contentful",
  "Noora",
  "Nudge (Actions)",
  "Nudgespot",
  "Olark",
  "OneSignal (New)",
  "Optimizely Advanced Audience Targeting",
  "Optimizely Data Platform",
  "Optimizely Feature Experimentation (Actions)",
  "Optimizely Full Stack",
  "Optimizely Web",
  "Orb",
  "Ortto",
  "Ortto (Actions)",
  "Pardot (Actions)",
  "Parsely",
  "Peaka",
  "Pendo",
  "Pendo Web (Actions)",
  "Perfect Audience",
  "Perkville",
  "PersistIQ",
  "Personas Facebook Custom Audiences",
  "Personyze",
  "Pingdom",
  "Pinterest Audiences",
  "Pinterest Conversions API",
  "Pinterest Tag",
  "Plotline",
  "Podsights",
  "Podscribe (Actions)",
  "Pointillist",
  "PostHog",
  "Postscript",
  "Proof Experiences",
  "ProfitWell",
  "ProsperStack",
  "Pushwoosh",
  "Qualtrics",
  "Quantcast",
  "QuanticMind",
  "Quora Conversion Pixel",
  "Rabble AI",
  "Recombee",
  "Reddit Audiences",
  "Reddit Conversions API",
  "Reddit Pixel",
  "Regal.io",
  "Refersion",
  "Refiner",
  "Rehook",
  "Repeater",
  "Responsys",
  "Retina",
  "RevX Cloud (Actions)",
  "Richpanel",
  "Rockerbox",
  "Rokt",
  "Rokt Audiences (Actions)",
  "Rollbar",
  "Rupt",
  "SaaSquatch v2",
  "Sailthru v2",
  "Salescamp CRM",
  "Salesforce (Actions)",
  "Salesforce Marketing Cloud (Actions)",
  "Salesmachine",
  "Saleswings (Actions)",
  "SatisMeter",
  "Savio",
  "Schematic",
  "ScopeAI",
  "Screeb",
  "Screeb Web (Actions)",
  "Scuba Analytics",
  "Segment Connections",
  "Segment Profiles",
  "SegMetrics",
  "Selligent Marketing Cloud",
  "SendGrid",
  "Sentry",
  "Serenytics",
  "ShareASale",
  "Sherlock",
  "SIGNL4 Alerting",
  "SimpleReach",
  "Singular",
  "SingleStore",
  "Skalin",
  "Slack",
  "Slack (Actions)",
  "SlicingDice",
  "Smartlook",
  "Snapboard",
  "Snapchat Audiences",
  "Snapchat Conversions API",
  "SnapEngage",
  "Spideo",
  "Sprig (Actions)",
  "Sprig Cloud",
  "Split",
  "StackAdapt Events & Conversions",
  "Startdeliver",
  "Startdeliver-v2",
  "Statsig",
  "Stories",
  "Stonly",
  "Stormly",
  "Subbly",
  "Survicate",
  "Survicate (Actions)",
  "Swrve",
  "Taboola (Actions)",
  "Talon.One",
  "Talon.One (Actions)",
  "Talkable",
  "Tamber",
  "Taplytics",
  "The Trade Desk CRM",
  "Trackier",
  "TrafficGuard",
  "Track JS",
  "tray.io",
  "Treasure Data",
  "Tractionboard",
  "Trustpilot",
  "TUNE",
  "Twilio Messaging",
  "Twitter Ads",
  "Unwaffle",
  "Upcall",
  "User.com",
  "UserGuiding",
  "UserIQ",
  "Userlist",
  "Userlens by Wudpecker",
  "Usermaven (Actions)",
  "UserMotion (Actions)",
  "Userpilot Cloud (Actions)",
  "Userpilot Mobile",
  "Userpilot Web (Actions)",
  "Userpilot Web Plugin",
  "UserVoice",
  "Variance",
  "Vero",
  "Vespucci",
  "Vidora",
  "Vitally",
  "Voucherify (Actions)",
  "VWO Cloud Mode (Actions)",
  "VWO Web Mode (Actions)",
  "WalkMe",
  "WebEngage",
  "Webhooks (Actions)",
  "Wigzo",
  "Windsor",
  "Wisepops",
  "Wishpond",
  "Woopra",
  "Xtremepush",
  "Xtremepush (Actions)",
  "Yahoo Audiences",
  "Yandex Metrica",
  "Youbora",
  "Zaius",
  "Zapier",
  "Zendesk",
  "Zopim",
];
